### ISSUE TITLE
Should we expect new episodes? 

### ISSUE THREAD

**Issue by LinArcX** [nixers-projects/podcast#6]
Hey guys. You're fantastic and awesome. Do you have any plan to continue this podcast?

**Comment by venam** [comment]
Hello @LinArcX ,  
I've left the audio format on the side and continued in article format. The next episode was supposed to be [this one about the role of distributions today](https://nixers.net/showthread.php?tid=2192&pid=19375#pid19375), which I've also posted on [my blog](https://venam.nixers.net/blog/unix/2020/03/29/distro-pkgs.html).

I might start recording again soon as I'm finding more time to do so.

**Comment by venam** [comment]
It's been a long time, but I've pushed a new episode.
